"""esquema inicial: corrida, cuenta y rechazo

Revision ID: 0001
Revises:
Create Date: 2026-09-29 11:51:26.986015
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corrida",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("iniciada_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terminada_en", sa.DateTime(timezone=True), nullable=True),
        sa.Column("origen", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("firma", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "estado",
            sa.Enum(
                "EN_PROCESO",
                "EXITOSA",
                "RECHAZADA",
                "FALLIDA",
                name="estado_corrida",
                native_enum=False,
                create_constraint=True,
                length=12,
            ),
            nullable=False,
        ),
        sa.Column("tolerancia_rechazo", sa.Float(), nullable=False),
        sa.Column("fecha_corte", sa.Date(), nullable=True),
        sa.Column("filas_leidas", sa.Integer(), nullable=False),
        sa.Column("filas_validas", sa.Integer(), nullable=False),
        sa.Column("filas_rechazadas", sa.Integer(), nullable=False),
        sa.Column("detalle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corrida")),
        sa.UniqueConstraint("run_id", name=op.f("uq_corrida_run_id")),
    )
    op.create_index(op.f("ix_corrida_iniciada_en"), "corrida", ["iniciada_en"], unique=False)
    op.create_index(
        "ux_corrida_firma_publicada",
        "corrida",
        ["firma"],
        unique=True,
        postgresql_where=sa.text("estado = 'EXITOSA'"),
    )
    op.create_table(
        "cuenta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("corrida_id", sa.Integer(), nullable=False),
        sa.Column("cliente_unico", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("saldo_total", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("dias_atraso", sa.Integer(), nullable=False),
        sa.Column("producto", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("canal", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("cve_entidad", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
        sa.Column("cve_municipio", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column("fecha_corte", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["corrida_id"], ["corrida.id"], name=op.f("fk_cuenta_corrida_id_corrida")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cuenta")),
        sa.UniqueConstraint(
            "corrida_id", "cliente_unico", name=op.f("uq_cuenta_corrida_id_cliente_unico")
        ),
    )
    op.create_index(op.f("ix_cuenta_cliente_unico"), "cuenta", ["cliente_unico"], unique=False)
    op.create_index(op.f("ix_cuenta_cve_entidad"), "cuenta", ["cve_entidad"], unique=False)
    op.create_index(op.f("ix_cuenta_fecha_corte"), "cuenta", ["fecha_corte"], unique=False)
    op.create_table(
        "rechazo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("corrida_id", sa.Integer(), nullable=False),
        sa.Column("fila", sa.Integer(), nullable=False),
        sa.Column("valores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("motivos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["corrida_id"], ["corrida.id"], name=op.f("fk_rechazo_corrida_id_corrida")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rechazo")),
        sa.UniqueConstraint("corrida_id", "fila", name=op.f("uq_rechazo_corrida_id_fila")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rechazo")
    op.drop_index(op.f("ix_cuenta_fecha_corte"), table_name="cuenta")
    op.drop_index(op.f("ix_cuenta_cve_entidad"), table_name="cuenta")
    op.drop_index(op.f("ix_cuenta_cliente_unico"), table_name="cuenta")
    op.drop_table("cuenta")
    op.drop_index(
        "ux_corrida_firma_publicada",
        table_name="corrida",
        postgresql_where=sa.text("estado = 'EXITOSA'"),
    )
    op.drop_index(op.f("ix_corrida_iniciada_en"), table_name="corrida")
    op.drop_table("corrida")
    # ### end Alembic commands ###
